version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      DB_DRIVER: "mysql"
      DSN: "root:Admin123@tcp(db:3306)/hexagonal"
    depends_on:
      - db

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_DATABASE: hexagonal
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

